# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: MyTest
on: 
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      
      - name: get secrets JSON
        run: each '${{ toJSON(secrets.MY_PASSWORD) }}'

      - name: get secrets password
        run: each '${{ secrets.MY_PASSWORD }}'
